### ISSUE TITLE
Issue with scraping programatically using provided code sample

### ISSUE THREAD

**Issue by Frank-P-Lu** [pedroallenrevez/jisho-api#7]
Hi there,

When I run the sample code provided for scraping programmatically:
```
from jisho_api.word import Word
from jisho_api.cli import scrape

word_requests = scrape(Word, ['water', 'fire'], '~/japanese/test')
```

I get this error:
```
Traceback (most recent call last):
  File "/home/frank/scripts/scrape_from_jisho.py", line 7, in <module>
    word_requests = scrape(Word, ['water', 'fire'], '~/japanese/test')
  File "/home/frank/dev/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/frank/dev/venv/lib/python3.8/site-packages/click/core.py", line 1042, in main
    args = list(args)
TypeError: 'type' object is not iterable
```

Help is appreciated. Thanks.

**Comment by pedroallenrevez** [comment]
Thanks for bringing this to attention.

I have taken care of the issue.
First, the README was wrongly written, secondly there was a bug in the correct call, which was solved as well.

You can now
```
from jisho_api import scrape
from jisho_api.word import Word

word_requests = scrape(Word, ['water', 'fire'], 'to/path/')
```
only the import has changed.

Cheers
